sudo: required
dist: trusty

language: python
cache: pip

# taken from Textract .travis.yml
before_install:
  - sudo ./travis-textract-requirements/debian.sh

# command to install dependencies
install:
  - ./travis-textract-requirements/python.sh
  - pip install tox

# command to run tests
script:
  - tox -e $TOXENV
# cache: pip
matrix:
  include:
    - env: TOXENV=py35-dj20-wt20
      python: 3.5
    - env: TOXENV=py36-dj20-wt20
      python: 3.6
    - env: TOXENV=py37-dj32-wt214
      python: 3.7
    - env: TOXENV=py38-dj32-wt214
      python: 3.8
    - env: TOXENV=py39-dj32-wt214
      python: 3.9
    - env: TOXENV=py310-dj32-wt214
      python: 3.10