# Generated by Django 2.0.4 on 2018-05-02 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0007_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtaildocs.Document')),
                ('transcription', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'document',
                'abstract': False,
            },
            bases=('wagtaildocs.document',),
        ),
    ]
