# Generated by Django 2.0.4 on 2018-05-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_textract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='transcription',
            field=models.TextField(default=''),
        ),
    ]
